# -*- coding: utf-8 -*-
"""Random _number _generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_Y4EF7KeaKto3PwTW9jU-cDNQO1LP-c
"""

import random
import sys

def generateRandomNumber(): 
    """ Function for generate random number
    
             between 1 and 100 
        returns:
         a random number between two given numbers  
    """
    randomNumber = random.randint(1,100)
    return randomNumber
def askuserForNumber (message = "Guess the number : "):
    """Function to ask user to guess what the number """ 

    userNumber = int(input(message))
    return userNumber
def checkUserNumber (userNumber , randomNumber):
    """Function checking the user number 
       
    """
    if userNumber > randomNumber :
        return "Too high"
    elif userNumber<randomNumber:
        return "Too Low"
    else : 
        return " Congratulations ! "


def main():# Main Function 
    user_name = input("Enter your name : ")
    print ("type of input user", type(user_name))
    print("Random Number Guessing")
    UserCongratulated =False # When the game start the user has been Conguralated
    LetsStart = True
    
    while UserCongratulated or LetsStart: # Any one of two variable is true will excuted While loop
        UserNumberOfGusses =0 # It keeps count of the number of guesses that user makes
        randomNumber = generateRandomNumber()
        userNumber = askuserForNumber() # Ask the user again the guess number and types of the number
        UserNumberOfGusses = UserNumberOfGusses + 1 
        message = checkUserNumber (userNumber , randomNumber )
       
      
      
        while message != " Congratulations ! " : # If the the meessage keep High or Low will ask te user keep on guessing
            print(message) # Print message if high or low
            userNumber = askuserForNumber ("Try Again: ")# Ask the user again the guess number with message "Try again"
            UserNumberOfGusses = UserNumberOfGusses + 1 # If the guesses number is wrong will be add one and exuted while loop untile get correct guess the number
            message = checkUserNumber (userNumber , randomNumber) # If the userName = randomNumber it will  return Congratulations
        print() 
        print(message , f" {user_name.capitalize()}  it took you" ,  UserNumberOfGusses,\
               "attempt to guess correctly\n" ) 
        try:
             f= open("scores.txt", "a" )
             f.write(f"Final Score for {user_name.capitalize()} is : { UserNumberOfGusses} \n")
        except :
              print("Something went wrong when opening the file")
        finally:
              f.close()
    
main()

"""# Nytt avsnitt

# Nytt avsnitt

# Nytt avsnitt
"""

